stages:
  - test
  - qa
  - package


pylint:
  stage: qa
  needs: []
  image: python:3
  script:
    - pip install pylint
    - pylint lib/check_mk/cee/dcd/plugins/connectors/csvconnector.py web/plugins/wato/csvconnector.py
  allow_failure: true


flake8:
  stage: qa
  needs: []
  image: python:3
  script:
    - pip install flake8
    - flake8 lib/check_mk/cee/dcd/plugins/connectors/csvconnector.py web/plugins/wato/csvconnector.py
  allow_failure: true


run tests:
  stage: test
  image: python:3
  script:
    - pip install pytest pytest-cov
    - pytest --junit-xml testreport.xml tests/
  artifacts:
    reports:
      junit: testreport.xml


create mkp:
  stage: package
  needs: ["run tests"]
  image: centos:7
  only:
    - tags
    - api
    - web
  script:
    # Converting info into info.json
    - python -c 'import json; f = open("info"); exec("j=%s" % f.read()); fj = open("info.json", "w"); json.dump(j, fj)'
    # Creating required tar files
    - tar -cv -C lib/ -f lib.tar check_mk/
    - tar -cv -C web/ -f web.tar plugins/wato/
    # Packing the final archive
    - tar -czvf csvconnector-${CI_COMMIT_REF_NAME}.mkp info info.json lib.tar web.tar
  artifacts:
    name: csvconnector-${CI_COMMIT_SHORT_SHA}
    paths:
      - csvconnector-${CI_COMMIT_REF_NAME}.mkp
