image: python:3

stages:
  - test
  - qa
  - package


pylint:
  stage: qa
  script:
    - pip install pylint
    - pylint --exit-zero lib/python/csvconnector.py web/plugins/wato/csvconnector.py


flake8:
  stage: qa
  script:
    - pip install flake8
    - flake8 --exit-zero lib/python/csvconnector.py web/plugins/wato/csvconnector.py


run tests:
  stage: test
  script:
    - pip install pytest pytest-cov
    - pytest --junit-xml testreport.xml --cov=csvconnector --cov-report term-missing tests/
  artifacts:
    reports:
      junit: testreport.xml


create mkp:
  stage: package
  image: centos:7
  only:
    - tags
    - api
    - web
  script:
    # Converting info into info.json
    - python -c 'import json; f = open("info"); exec("j=%s" % f.read()); fj = open("info.json", "w"); json.dump(j, fj)'
    # Creating required tar files
    - tar -cv -C lib/ -f lib.tar python/
    - tar -cv -C web/ -f web.tar plugins/wato/
    # Packing the final archive
    - tar -czvf csvconnector-${CI_COMMIT_REF_NAME}.mkp info info.json lib.tar web.tar
  artifacts:
    name: csvconnector-${CI_COMMIT_SHORT_SHA}
    paths:
      - csvconnector-${CI_COMMIT_REF_NAME}.mkp