image: centos:7

stages:
  - package

create mkp:
  stage: package
  only:
    - tags
    - api
    - web
  script:
    # Converting info into info.json
    - python -c 'import json; f = open("info"); exec("j=%s" % f.read()); fj = open("info.json", "w"); json.dump(j, fj)'
    # Creating required tar files
    - tar -cv -C bin/ -f bin.tar dcd
    - tar -cv -C lib/ -f lib.tar python/
    - tar -cv -C web/ -f web.tar plugins/wato/
    # Packing the final archive
    - tar -czvf csvconnector-${CI_COMMIT_REF_NAME}.mkp info info.json bin.tar lib.tar web.tar
  artifacts:
    name: csvconnector-${CI_COMMIT_SHORT_SHA}
    paths:
      - csvconnector-${CI_COMMIT_REF_NAME}.mkp